mkchrootpkg: backport arch patches

diff --git a/bin/mkchrootpkg.in b/bin/mkchrootpkg.in
--- a/bin/mkchrootpkg.in
+++ b/bin/mkchrootpkg.in
@@ -185,9 +185,10 @@ EOF
     {
         printf '#!/bin/bash\n'
         declare -f _chrootbuild
+        declare -p SOURCE_DATE_EPOCH 2>/dev/null || true
         printf '_chrootbuild "$@" || exit\n'
 
-        if $run_namcap; then
+        if [[ $run_namcap = true ]]; then
             declare -f _chrootnamcap
             printf '_chrootnamcap || exit\n'
         fi
@@ -201,7 +202,7 @@ _chrootbuild() {
     exec </dev/console
     export LANG=en_US.UTF-8
     . /etc/profile
-    sudo -iu builduser bash -c 'cd /startdir; makepkg "$@"' -bash "$@"
+    sudo --preserve-env=SOURCE_DATE_EPOCH -iu builduser bash -c 'cd /startdir; makepkg "$@"' -bash "$@"
 }
 
 _chrootnamcap() {
@@ -218,17 +219,16 @@ _chrootnamcap() {
 #  - USER
 download_sources() {
     local copydir=$1
-    local src_owner=$2
+    local makepkg_user=$2
 
-    local builddir="$(mktemp -d)"
+    local builddir
+    builddir="$(mktemp -d)"
     chmod 1777 "$builddir"
 
     # Ensure sources are downloaded
-    makepkg_user=${makepkg_user:-$SUDO_USER}
     sudo -u "$makepkg_user" env SRCDEST="$SRCDEST" BUILDDIR="$builddir" \
-    makepkg --config="$copydir/etc/makepkg.conf" --verifysource -o ||
-    die "Could not download sources."
-    (( $? != 0 )) && die "Could not download sources."
+        makepkg --config="$copydir/etc/makepkg.conf" --verifysource -o ||
+        die "Could not download sources."
 
     # Clean up garbage from verifysource
     rm -rf "$builddir"
@@ -263,6 +263,11 @@ move_products() {
     for s in "$copydir"/srcpkgdest/*; do
         chown "$src_owner" "$s"
         mv "$s" "$SRCPKGDEST"
+
+        # Fix broken symlink because of temporary chroot SRCPKGDEST /srcpkgdest
+        if [[ "$PWD" != "$SRCPKGDEST" && -L "$PWD/${s##*/}" ]]; then
+            ln -sf "$SRCPKGDEST/${s##*/}"
+        fi
     done
 }
 # }}}
@@ -376,7 +381,7 @@ main() {
 
     download_sources "$copydir" "$src_owner"
 
-    prepare_chroot "$copydir" "$USER_HOME" "$keepbuilddir"
+    prepare_chroot "$copydir" "$USER_HOME" "$keepbuilddir" "$run_namcap"
 
     bindmounts_rw+=("${PWD}:/startdir" "${SRCDEST}:/srcdest")
 
